-- Supabase schema for LEE TECH SERVICES

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  link text default '',
  image text default '',
  created_at timestamptz default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  content text not null,
  created_at timestamptz default now()
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text default '',
  date text default '',
  created_at timestamptz default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null,
  text text not null,
  date text default '',
  created_at timestamptz default now()
);

alter table public.projects enable row level security;
alter table public.announcements enable row level security;
alter table public.logs enable row level security;
alter table public.comments enable row level security;

create policy "Public read access for projects" on public.projects
for select using (true);

create policy "Public read access for announcements" on public.announcements
for select using (true);

create policy "Public read access for logs" on public.logs
for select using (true);

create policy "Public read access for comments" on public.comments
for select using (true);

create policy "Allow anon insert for projects" on public.projects
for insert with check (true);

create policy "Allow anon insert for announcements" on public.announcements
for insert with check (true);

create policy "Allow anon insert for logs" on public.logs
for insert with check (true);

create policy "Allow anon insert for comments" on public.comments
for insert with check (true);

create policy "Allow anon update for projects" on public.projects
for update using (true) with check (true);

create policy "Allow anon update for announcements" on public.announcements
for update using (true) with check (true);

create policy "Allow anon update for logs" on public.logs
for update using (true) with check (true);

create policy "Allow anon update for comments" on public.comments
for update using (true) with check (true);

create policy "Allow anon delete for projects" on public.projects
for delete using (true);

create policy "Allow anon delete for announcements" on public.announcements
for delete using (true);

create policy "Allow anon delete for logs" on public.logs
for delete using (true);

create policy "Allow anon delete for comments" on public.comments
for delete using (true);
